server:
    port:
      8888
spring:
      cloud:
          config:
              server:
                    git:
                      uri: https://github.com/rahulsmorecapgemini/pluralsight-spring-cloudconfig-wa-tolls-2
# clone-on-start: true

#  profiles:
#    active:
#    native:
#          search-locations: classpath:/config